//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Турагенство.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DA_1Entities : DbContext
    {
        public DA_1Entities()
            : base("name=DA_1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HotelPhoto> HotelPhoto { get; set; }
        public virtual DbSet<name> name { get; set; }
        public virtual DbSet<PostID> PostID { get; set; }
        public virtual DbSet<Service> Service { get; set; }
        public virtual DbSet<ServiceByTour> ServiceByTour { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public static name currentuser;

    }
}
