//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Турагенство.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class name
    {
        public int ID { get; set; }
        public string Name1 { get; set; }
        public Nullable<int> Post { get; set; }
        public string Password { get; set; }
        public string photo { get; set; }
    }
}
