//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Благодать.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string Full_name { get; set; }
        public int Client_s_code { get; set; }
        public string Passport_data { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Adress { get; set; }
        public string E_mail { get; set; }
        public string Password { get; set; }
    }
}
