//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Благодать.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int ID { get; set; }
        public string Order_s_code { get; set; }
        public Nullable<System.DateTime> Date_of_creation { get; set; }
        public Nullable<System.TimeSpan> Order_time { get; set; }
        public Nullable<int> Client_s_code { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> Closing_date { get; set; }
        public string Rental_time { get; set; }
    
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
